Merged PR 1296659: Use static_assert to ensure the use of WinRT types and produce simpler error messages
This update adds a simple type trait that the projection can use to assert that a given type is a WinRT type. I have used this type trait to add static_assert declarations wherever a user-provided type is expected to be a WinRT type. This produces dramatically better error messages when an unsupported type is used. For example, the following erroneous code:

```C++
IVector<std::wstring> v;
```

Produces the following error messages:

```
error C2338: T must be WinRT type.
sample.cpp(9): note: see reference to class template instantiation 'winrt::Windows::Foundation::Collections::IVector<std::wstring>' being compiled
```

The first line explains the problem. The second line points directly to the user-attempted instantiation and thus quickly gets the developer looking at the problem.

By contrast, this code actually compiled before (that's bad). Only when you attempted to create an instance did you get the following rather cryptic errors:

```
error C2665: 'winrt::detach_abi': none of the 3 overloads could convert all the argument types
note: could be 'void *winrt::detach_abi(std::nullptr_t) noexcept'
note: or       'void *winrt::detach_abi(winrt::Windows::Foundation::IUnknown &&) noexcept'
note: or       'void *winrt::detach_abi(winrt::Windows::Foundation::IUnknown &) noexcept'
note: while trying to match the argument list '(std::wstring)'
.
.
.
etc.
```

Related work items: #15300077